CREATE TABLE `TB_USER`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '회원 고유 ID. 시스템 내에서 사용자를 식별하는 기본키',
    `EMAIL` VARCHAR(100) NOT NULL COMMENT '회원 이메일. 로그인 ID 또는 계정 식별용',
    `PASSWORD` VARCHAR(255) NULL COMMENT '회원 비밀번호. 해시 형태로 저장',
    `KAKAO_ID` VARCHAR(50) NULL COMMENT '카카오 로그인 연동 ID. 소셜 로그인 시 사용',
    `NAME` VARCHAR(50) NOT NULL COMMENT '회원 이름. 화면 표시용',
    `ROLE` VARCHAR(10) NOT NULL DEFAULT 'USER' COMMENT '회원 권한. 예: USER, ADMIN 등',
    `CREATED_AT` DATETIME NULL COMMENT '가입일',
    `UPDATED_AT` DATETIME NULL COMMENT '수정일'
);
ALTER TABLE
    `TB_USER` ADD UNIQUE `tb_user_email_unique`(`EMAIL`);
ALTER TABLE
    `TB_USER` ADD UNIQUE `tb_user_kakao_id_unique`(`KAKAO_ID`);
CREATE TABLE `TB_STORE`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `USER_ID` INT NOT NULL,
    `CATEGORY` VARCHAR(100) NULL COMMENT '한식? 중식? 이런 데이터 관리한다',
    `NAME` VARCHAR(100) NOT NULL,
    `ADDRESS` VARCHAR(255) NOT NULL,
    `LATITUDE` DECIMAL(10, 8) NOT NULL COMMENT '위도 좌표. 지도 표시 및 거리 계산용',
    `LONGITUDE` DECIMAL(11, 8) NOT NULL COMMENT '경도',
    `TEL_NUMBER` VARCHAR(20) NULL,
    `DESCRIPTION` TEXT NULL,
    `IS_APPROVED` TINYINT(1) NOT NULL COMMENT '관리자 승인 여부. 0=미승인, 1=승인',
    `CREATED_AT` DATETIME NULL,
    `UPDATED_AT` DATETIME NULL,
    `HASH_TAG` VARCHAR(255) NULL COMMENT '해시태그',
    `EATING_TIME` VARCHAR(20) NULL
);
ALTER TABLE
    `TB_STORE` ADD INDEX `tb_store_latitude_longitude_index`(`LATITUDE`, `LONGITUDE`);
ALTER TABLE
    `TB_STORE` ADD INDEX `tb_store_name_index`(`NAME`);
CREATE TABLE `TB_REVIEW`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '맛집ID : TB_STORE-ID',
    `USER_ID` INT NOT NULL,
    `STORE_ID` INT NOT NULL,
    `POINT_01` TINYINT NOT NULL COMMENT '점수 (맛)',
    `POINT_02` TINYINT NOT NULL COMMENT '점수 (가격)',
    `POINT_03` TINYINT NOT NULL COMMENT '점수 (친절도)',
    `CONTENT` TEXT NULL,
    `CREATED_AT` DATETIME NULL,
    `UPDATED_AT` DATETIME NULL,
    `ORDERED_ITEM` VARCHAR(255) NOT NULL COMMENT '주문한 메뉴 (뭘 먹고 리뷰남기는거냐?)'
);
ALTER TABLE
    `TB_REVIEW` ADD INDEX `tb_review_store_id_index`(`STORE_ID`);
CREATE TABLE `TB_PICTURE`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `REVIEW_ID` INT NOT NULL,
    `URL` VARCHAR(255) NOT NULL,
    `IS_MAIN` TINYINT(1) NOT NULL,
    `CREATED_AT` DATETIME NULL
);
CREATE TABLE `TB_MENU`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `STORE_ID` INT NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `PRICE` INT NOT NULL COMMENT '정수형 (단위 : 원)',
    `DESCRIPTION` TEXT NULL,
    `CREATED_AT` DATETIME NULL,
    `UPDATED_AT` DATETIME NULL,
    `IS_RECOMMANDED` TINYINT NULL
);
ALTER TABLE
    `TB_MENU` ADD INDEX `tb_menu_store_id_index`(`STORE_ID`);
ALTER TABLE
    `TB_STORE` ADD CONSTRAINT `tb_store_user_id_foreign` FOREIGN KEY(`USER_ID`) REFERENCES `TB_USER`(`ID`);
ALTER TABLE
    `TB_MENU` ADD CONSTRAINT `tb_menu_store_id_foreign` FOREIGN KEY(`STORE_ID`) REFERENCES `TB_STORE`(`ID`);
ALTER TABLE
    `TB_PICTURE` ADD CONSTRAINT `tb_picture_review_id_foreign` FOREIGN KEY(`REVIEW_ID`) REFERENCES `TB_REVIEW`(`ID`);
ALTER TABLE
    `TB_REVIEW` ADD CONSTRAINT `tb_review_store_id_foreign` FOREIGN KEY(`STORE_ID`) REFERENCES `TB_STORE`(`ID`);
ALTER TABLE
    `TB_REVIEW` ADD CONSTRAINT `tb_review_user_id_foreign` FOREIGN KEY(`USER_ID`) REFERENCES `TB_USER`(`ID`);
